
package Interfaces;

import BOs.PlatilloBO;
import Tablas.Platillo;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Carlos Ulibarri
 */
public class Platillo_I extends javax.swing.JFrame {

    PlatilloBO pBO = new PlatilloBO();
    Platillo plt =  new Platillo();
    /**
     * Creates new form Platillo_I
     */
    public Platillo_I() {
        initComponents();
        mostrarPlatillosT();
        
        this.setLocationRelativeTo(null);
    }
   
   
    public void mostrarPlatillosT (){
        pBO.mostrarPlatillo(tb_pla);
        tb_pla.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_pla.getColumnModel().getColumn(3).setMaxWidth(0);
        tb_pla.getColumnModel().getColumn(5).setMaxWidth(0);
        
        tb_pla.getColumnModel().getColumn(1).setPreferredWidth(300);
        tb_pla.getColumnModel().getColumn(2).setPreferredWidth(900);
        //tb_pla.setRowHeight(100);
    }
    
    public void limpiar(){
        String l = "";
        tx_pla_n.setText(l);
        tx_pla_desc.setText(l);
        tx_pla_c.setText(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondo();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_pla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tx_pla_n = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_pla_desc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_pla_c = new javax.swing.JTextField();
        b_reporte = new javax.swing.JButton();
        b_agregar = new javax.swing.JButton();
        b_editar1 = new javax.swing.JButton();
        b_borrar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tx_pla_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_pla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tb_pla.setForeground(new java.awt.Color(0, 0, 0));
        tb_pla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_pla.setGridColor(new java.awt.Color(0, 0, 0));
        tb_pla.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tb_pla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tb_pla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_plaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_pla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 760, 150));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Platillos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        tx_pla_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_pla_nActionPerformed(evt);
            }
        });
        jPanel1.add(tx_pla_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tx_pla_desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx_pla_descMouseClicked(evt);
            }
        });
        tx_pla_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_pla_descActionPerformed(evt);
            }
        });
        jPanel1.add(tx_pla_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 590, 80));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        tx_pla_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_pla_cActionPerformed(evt);
            }
        });
        jPanel1.add(tx_pla_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, -1));

        b_reporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\reporte.png")); // NOI18N
        jPanel1.add(b_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 30, 30));

        b_agregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\nuevo.png")); // NOI18N
        b_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(b_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 30, 30));

        b_editar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\editar.png")); // NOI18N
        b_editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editar1ActionPerformed(evt);
            }
        });
        jPanel1.add(b_editar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 30, 30));

        b_borrar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\borrar.png")); // NOI18N
        b_borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(b_borrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 30, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 100, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 470));
        getContentPane().add(tx_pla_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_pla_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_pla_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_pla_nActionPerformed

    private void tx_pla_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_pla_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_pla_descActionPerformed

    private void tx_pla_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_pla_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_pla_cActionPerformed

    private void b_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregarActionPerformed
        if(tx_pla_n.getText().isEmpty() || tx_pla_desc.getText().isEmpty() || 
           tx_pla_c.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Deben estar llenos todos los campos" );
        }else{
            plt.setPt_nom(tx_pla_n.getText());
            plt.setPt_desc(tx_pla_desc.getText());
            plt.setPt_cost(Integer.parseInt(tx_pla_c.getText()));
            String mensaje = pBO.agregarPlatillo(plt);
            limpiar();
            mostrarPlatillosT();
        }
    }//GEN-LAST:event_b_agregarActionPerformed

    private void b_editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editar1ActionPerformed
        if(tx_pla_n.getText().isEmpty() || tx_pla_desc.getText().isEmpty() || 
           tx_pla_c.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Deben estar llenos todos los campos" );
        }else{
            
            plt.setPt_nom(tx_pla_n.getText());
            plt.setPt_desc(tx_pla_desc.getText());
            plt.setPt_cost(Integer.parseInt(tx_pla_c.getText()));
            String mensaje = pBO.editarPlatillo(plt,Integer.parseInt(tx_pla_id.getText()));
            limpiar();
            mostrarPlatillosT();
        }
    }//GEN-LAST:event_b_editar1ActionPerformed

    private void b_borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrar1ActionPerformed
        String mensaje = pBO.borrarPlatillo(Integer.parseInt(tx_pla_id.getText()));
            limpiar();
            mostrarPlatillosT();
    }//GEN-LAST:event_b_borrar1ActionPerformed

    private void tx_pla_descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx_pla_descMouseClicked
       
       
    }//GEN-LAST:event_tx_pla_descMouseClicked

    private void tb_plaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_plaMouseClicked
       int sel = tb_pla.rowAtPoint(evt.getPoint());
        
       tx_pla_id.setText(tb_pla.getValueAt(sel, 0)+"");
       tx_pla_n.setText(tb_pla.getValueAt(sel, 1)+"");     
       tx_pla_desc.setText(tb_pla.getValueAt(sel, 2)+"");
       tx_pla_c.setText(tb_pla.getValueAt(sel, 4)+"");
    }//GEN-LAST:event_tb_plaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Platillo_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Platillo_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Platillo_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platillo_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Platillo_I().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_agregar;
    private javax.swing.JButton b_borrar1;
    private javax.swing.JButton b_editar1;
    private javax.swing.JButton b_reporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_pla;
    private javax.swing.JTextField tx_pla_c;
    private javax.swing.JTextField tx_pla_desc;
    private javax.swing.JTextField tx_pla_id;
    private javax.swing.JTextField tx_pla_n;
    // End of variables declaration//GEN-END:variables
    class Fondo extends JPanel {
        private Image img;
        
        @Override
        public void paint(Graphics g){
            img = new ImageIcon(getClass().getResource("/img/wallrest.png")).getImage();
            g.drawImage(img, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
