
package Interfaces;

import BOs.RepartidorBO;
import Tablas.Repartidor;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Carlos Ulbarri
 */
public class Repartidor_I extends javax.swing.JFrame {
    String itemcombmet ,itemcombcal;
    Fondo f = new Fondo();
    RepartidorBO rBO = new RepartidorBO();
    Repartidor rep =  new Repartidor();
    /**
     * Creates new form Repartidor_I
     */
    public Repartidor_I() {
        
        //this.setContentPane(f);
        initComponents();
        mostrarRepartidoresT();
        this.setLocationRelativeTo(null);
    }
    
    public void mostrarRepartidoresT (){
        rBO.mostrarRep(tb_rep);
        tb_rep.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    public void limpiar(){
        String l = "";
        tx_rep_n.setText(l);
        tx_rep_ap.setText(l);
        tx_rep_am.setText(l);
        tx_rep_cor.setText(l);
        tx_rep_tel.setText(l);
        tx_rep_u.setText(l);
        tx_rep_contra.setText(l);
        comb_rep_ent.setSelectedItem("Seleccionar");
        comb_rep_cal.setSelectedItem("Seleccionar");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Fondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_rep = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tx_rep_n = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tx_rep_ap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_rep_am = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tx_rep_tel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_rep_cor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tx_rep_u = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tx_rep_contra = new javax.swing.JTextField();
        comb_rep_cal = new javax.swing.JComboBox<>();
        comb_rep_ent = new javax.swing.JComboBox<>();
        b_reporte = new javax.swing.JButton();
        b_agregar = new javax.swing.JButton();
        b_editar1 = new javax.swing.JButton();
        b_borrar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tx_rep_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_rep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_rep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_repMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_rep);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 960, 190));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("Repartidores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 260, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel1.add(tx_rep_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido paterno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));
        jPanel1.add(tx_rep_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido materno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));
        jPanel1.add(tx_rep_am, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 130, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));
        jPanel1.add(tx_rep_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 130, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(tx_rep_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));
        jPanel1.add(tx_rep_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 130, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        jPanel1.add(tx_rep_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 130, -1));

        comb_rep_cal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comb_rep_cal.setForeground(new java.awt.Color(255, 255, 255));
        comb_rep_cal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1 Estrella", "2 Estrellas", "3 Estrellas", "4 Estrellas", "5 Estrellas" }));
        jPanel1.add(comb_rep_cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 140, -1));

        comb_rep_ent.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        comb_rep_ent.setForeground(new java.awt.Color(255, 255, 255));
        comb_rep_ent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "A Pie", "Automovil", "Bicicleta", "Motocicleta" }));
        jPanel1.add(comb_rep_ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 140, -1));

        b_reporte.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\reporte.png")); // NOI18N
        jPanel1.add(b_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 30, 30));

        b_agregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\nuevo.png")); // NOI18N
        b_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(b_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 30, 30));

        b_editar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\editar.png")); // NOI18N
        b_editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editar1ActionPerformed(evt);
            }
        });
        jPanel1.add(b_editar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 30, 30));

        b_borrar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\green\\Desktop\\Base de Datos_Negocio\\Proyecto\\borrar.png")); // NOI18N
        b_borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(b_borrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 30, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 90, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 51));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 450));
        getContentPane().add(tx_rep_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregarActionPerformed
        
        
        itemcombmet = comb_rep_ent.getSelectedItem().toString();
        itemcombcal = comb_rep_cal.getSelectedItem().toString();
        
        if(tx_rep_n.getText().isEmpty() || tx_rep_ap.getText().isEmpty() || tx_rep_am.getText().isEmpty() || 
           tx_rep_cor.getText().isEmpty() || tx_rep_tel.getText().isEmpty() || tx_rep_u.getText().isEmpty() ||
           tx_rep_contra.getText().isEmpty() || itemcombmet.equals("Seleccionar") || 
           itemcombcal.equals("Seleccionar")){
           JOptionPane.showMessageDialog(null, "Deben estar llenos todos los campos" );
        }else{
           // Cliente cnt =  new Cliente();
           String met, cal;
       
            if(itemcombmet.equals("A Pie")){
                met = "A Pie";
            }else if(itemcombmet.equals("Automovil")){
                met = "Automovil";
            }else if(itemcombmet.equals("Bicicleta")){
                met = "Bicicleta";
            }else{
                met = "Motocicleta";
            }
            
            if(itemcombcal.equals("1 Estrella")){
                cal = "1 Estrella";
            }else if(itemcombcal.equals("2 Estrellas")){
                cal = "2 Estrellas";
            }else if(itemcombcal.equals("3 Estrellas")){
                cal = "3 Estrellas";
            }else if(itemcombcal.equals("4 Estrellas")){
                cal = "4 Estrellas";
            }else{
                cal = "5 Estrellas";
            }
            rep.setRep_nom(tx_rep_n.getText());
            rep.setRep_ap(tx_rep_ap.getText());
            rep.setRep_am(tx_rep_am.getText());
            rep.setRep_correo(tx_rep_cor.getText());
            rep.setRep_tel(Long.parseLong(tx_rep_tel.getText()));
            rep.setRep_usu(tx_rep_u.getText());
            rep.setRep_contra(tx_rep_contra.getText());
            rep.setRep_met_ent(met);
            rep.setRep_cal(cal);
            String mensaje = rBO.agregarRep(rep);
            limpiar();
            mostrarRepartidoresT();
        }
    }//GEN-LAST:event_b_agregarActionPerformed

    private void b_editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editar1ActionPerformed
        
        
        itemcombmet = comb_rep_ent.getSelectedItem().toString();
        itemcombcal = comb_rep_cal.getSelectedItem().toString();
        
        if(tx_rep_n.getText().isEmpty() || tx_rep_ap.getText().isEmpty() || tx_rep_am.getText().isEmpty() || 
           tx_rep_cor.getText().isEmpty() || tx_rep_tel.getText().isEmpty() || tx_rep_u.getText().isEmpty() ||
           tx_rep_contra.getText().isEmpty() || itemcombmet.equals("Seleccionar") || 
           itemcombcal.equals("Seleccionar")){
           JOptionPane.showMessageDialog(null, "Deben estar llenos todos los campos" );
        }else{
           // Cliente cnt =  new Cliente();
           String met, cal;
            if(itemcombmet.equals("A Pie")){
                met = "A Pie";
            }else if(itemcombmet.equals("Automovil")){
                met = "Automovil";
            }else if(itemcombmet.equals("Bicicleta")){
                met = "Bicicleta";
            }else{
                met = "Motocicleta";
            }
            
            if(itemcombcal.equals("1 Estrella")){
                cal = "1 Estrella";
            }else if(itemcombcal.equals("2 Estrellas")){
                cal = "2 Estrellas";
            }else if(itemcombcal.equals("3 Estrellas")){
                cal = "3 Estrellas";
            }else if(itemcombcal.equals("4 Estrellas")){
                cal = "4 Estrellas";
            }else{
                cal = "5 Estrellas";
            }
            rep.setRep_id(Integer.parseInt(tx_rep_id.getText()));
            rep.setRep_nom(tx_rep_n.getText());
            rep.setRep_ap(tx_rep_ap.getText());
            rep.setRep_am(tx_rep_am.getText());
            rep.setRep_correo(tx_rep_cor.getText());
            rep.setRep_tel(Long.parseLong(tx_rep_tel.getText()));
            rep.setRep_usu(tx_rep_u.getText());
            rep.setRep_contra(tx_rep_contra.getText());
            rep.setRep_met_ent(met);
            rep.setRep_cal(cal);
            String mensaje = rBO.editarRep(rep,Integer.parseInt(tx_rep_id.getText()));
            limpiar();
            mostrarRepartidoresT();
        }
    }//GEN-LAST:event_b_editar1ActionPerformed

    private void b_borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrar1ActionPerformed
        String mensaje = rBO.borrarRep(Integer.parseInt(tx_rep_id.getText()));
        limpiar();
        mostrarRepartidoresT();
    }//GEN-LAST:event_b_borrar1ActionPerformed

    private void tb_repMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_repMouseClicked
         int sel = tb_rep.rowAtPoint(evt.getPoint());
       
       
       tx_rep_id.setText(tb_rep.getValueAt(sel, 0)+"");
       tx_rep_n.setText(tb_rep.getValueAt(sel, 1)+"");     
       tx_rep_ap.setText(tb_rep.getValueAt(sel, 2)+"");
       tx_rep_am.setText(tb_rep.getValueAt(sel, 3)+"");
       tx_rep_tel.setText(tb_rep.getValueAt(sel, 4)+"");
       tx_rep_cor.setText(tb_rep.getValueAt(sel, 5)+"");
       tx_rep_u.setText(tb_rep.getValueAt(sel, 6)+"");
       tx_rep_contra.setText(tb_rep.getValueAt(sel, 7)+"");
       
       
       itemcombmet = tb_rep.getValueAt(sel, 8)+"";
       itemcombcal = tb_rep.getValueAt(sel, 9)+"";
       if(itemcombmet.equals("A Pie")){
            comb_rep_ent.setSelectedItem("A Pie");
        }else if(itemcombmet.equals("Automovil")){
            comb_rep_ent.setSelectedItem("Automovil");
        }else if(itemcombmet.equals("Bicicleta")){
            comb_rep_ent.setSelectedItem("Bicicleta");
        }else{
            comb_rep_ent.setSelectedItem("Motocicleta");
        }
            
        if(itemcombcal.equals("1 Estrella")){
            comb_rep_cal.setSelectedItem("1 Estrella");
        }else if(itemcombcal.equals("2 Estrellas")){
            comb_rep_cal.setSelectedItem("2 Estrellas");
        }else if(itemcombcal.equals("3 Estrellas")){
            comb_rep_cal.setSelectedItem("3 Estrellas");
        }else if(itemcombcal.equals("4 Estrellas")){
            comb_rep_cal.setSelectedItem("4 Estrellas");
        }else{
            comb_rep_cal.setSelectedItem("5 Estrellas");
        }
    }//GEN-LAST:event_tb_repMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Repartidor_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Repartidor_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Repartidor_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Repartidor_I.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Repartidor_I().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_agregar;
    private javax.swing.JButton b_borrar1;
    private javax.swing.JButton b_editar1;
    private javax.swing.JButton b_reporte;
    private javax.swing.JComboBox<String> comb_rep_cal;
    private javax.swing.JComboBox<String> comb_rep_ent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_rep;
    private javax.swing.JTextField tx_rep_am;
    private javax.swing.JTextField tx_rep_ap;
    private javax.swing.JTextField tx_rep_contra;
    private javax.swing.JTextField tx_rep_cor;
    private javax.swing.JTextField tx_rep_id;
    private javax.swing.JTextField tx_rep_n;
    private javax.swing.JTextField tx_rep_tel;
    private javax.swing.JTextField tx_rep_u;
    // End of variables declaration//GEN-END:variables
    class Fondo extends JPanel {
        private Image img;
        
        @Override
        public void paint(Graphics g){
            img = new ImageIcon(getClass().getResource("/img/wallrest.png")).getImage();
            g.drawImage(img, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
